### ISSUE TITLE
Replace Known Tokens only works 1 time

### ISSUE THREAD

**Issue by bbouldin** [chrisGerken/transformAuthoring#4]
The right-click menu "Replace Known Tokens" works the first time, but not after that point.

**Comment by chrisGerken** [comment]
pushed to gramar.org/eclipse/xaa update site.

Updates in the XAA editor are immediately pushed to an in-memory cache which is accessed by the refactoring wizard.  Lazy initialization from the workspace occurs if the model hasn't been edited, yet, in this workspace session.
